### PR TITLE
Added support of Russian "zae.bz" (very simple) service

### PR DESCRIPTION
**Pull request by p0deje**
It required to add `Service#post` method with corresponding test.

### CODE REVIEW

**Comment by p0deje** [comment]
Any plans to merge this?

**Comment by rafmagana** [comment]
Hey, thanks for bumping this up, I will review it tonight. Thanks a lot. You forgot to add your binary to the list of executables in the gemspec, but I'll do it.

**Comment by p0deje** [comment]
@rafmagana bumping it up again :tangerine:

**Comment by rafmagana** [comment]
Thanks a lot and excuse me for the delay.

**Comment by rafmagana** [comment]
FYI new v0.3.0 released

**Pull request merged**
